project_id = "ml-project-340322"
region     = "europe-west1"
bucket_name_prefix = "mlflow-storage"
user_name = "admin"
user_password = "admin"
vpc_name = "ml-project-340322-vpc"
subnet_cidr_range = "10.10.0.0/24"
